"""Added hobby attr to User

Revision ID: 36f50c24dc93
Revises: 3d441fdb8444
Create Date: 2013-09-30 19:36:51.866208

"""

# revision identifiers, used by Alembic.
revision = '36f50c24dc93'
down_revision = '3d441fdb8444'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hobby', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hobby')
    ### end Alembic commands ###
