"""change2

Revision ID: 3d441fdb8444
Revises: 4d6527b82992
Create Date: 2013-09-30 19:33:16.863979

"""

# revision identifiers, used by Alembic.
revision = '3d441fdb8444'
down_revision = '4d6527b82992'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
